// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Label struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Memo struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
	Label *Label `json:"label"`
}

type NewMemo struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}
